defaults:
  - _self_
  - benchmark: hotpotqa
  - agent: expel
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled    

ai_name: ${benchmark.ai_name}
agent_type: ${agent.name}
log_dir: logs
testing: true
resume: false
load_cache_rules: true
no_rules: false
run_name: run
load_run_name: ${run_name}

# remove hydra output files
hydra:  
  output_subdir: null  
  run:  
    dir: .