defaults:
  - _self_
  - benchmark: hotpotqa
  - agent: expel
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
ai_name: ${benchmark.ai_name}
agent_type: ${agent.name}
log_dir: logs
run_name: run
load_run_name: ${run_name}
testing: true
folded: true
resume: false
resume_fold: -1
seed: 42

# remove hydra output files
hydra:  
  output_subdir: null  
  run:  
    dir: .